services:
  - type: web
    name: domestic-services-backend
    env: node
    plan: free
    rootDir: domestic-services-backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production